/*  TSMA.c  - this file auto generated by tools */

/* modification history
-----------------------

01c 2020-03-18 19:12:30   减少线程个数，mio里处理了运动，软件只要设置寄存器即可
01b 2016-07-11 20:14:50   修改为主任务多线程方式
01a 2016-05-05 11:00:17     auto create by autogen moban tool
*/

/*
<autogen moban tool>
  author: frank
  bug report: frank_zhou@163.com
*/




#define  TSMA_C

#include <windows.h>
#include <stdarg.h>

#include    "golytec.h"
#include    "DNXA.h"

#include    "libTSXA.h"
#include    "TSAP.h"
#include    "TSXI.h"
#include    "GFXA.h"




#pragma comment(lib,"ws2_32.lib")



//#define  DTXA_trace_t  




#undef  TS_DEBUG

#ifdef      TS_DEBUG
int TS_LOG(char *func_name, char *format, ...)
{
    char str[512];
    va_list  arg;

    memset((void *)str, 0, sizeof(str));

    va_start(arg, format);
    vsprintf(str, format, arg);
    va_end(arg);
    DTXA_trace_t("TS", 2, func_name, str);

    return 0;
}
#else
int TS_LOG(char *func_name, char *format, ...)
{
    return 0;
}
#endif





// 按最多8个动子来设置
// thread pipe分配如下: 
#define     TSMA_MAX_PIPE_DATA_SIZE         8192

#define     TSMA_MAX_THREAD_NUM             8       

#define     TSMA_PIPE_NUM_MAIN_THREAD       0
#define     TSMA_PIPE_NUM_GROUP_WAIT        1  
#define     TSMA_PIPE_NUM_MIO_READ_WRITE     2
#define     TSMA_PIPE_NUM_DIANJIAO_THREAD    3
#define     TSMA_PIPE_NUM_ZHUZHUANG_THREAD    4


// 全局变量
TSXI_REQ_MSG_struct  TSMA_req_msg;      // MA的接收缓冲
TSXI_RPL_MSG_struct  TSMA_rpl_msg;      // MA的回应消息缓冲
int TSMA_replyAddr = 0;                 // 回应地址



HANDLE g_TSMA_pipe_server_fd[TSMA_MAX_THREAD_NUM];          // pipe client fd
HANDLE g_TSMA_pipe_client_fd[TSMA_MAX_THREAD_NUM];          // pipe server fd

BOOL g_TSMA_thread_stop = FALSE;                        // stop threads



// forward defines
int  TSMA_dispatch( TSXI_FUNC_enum          fc,
                    TSXI_REQ_MSG_struct     *rq_msg,
                    TSXI_RPL_MSG_struct     *rp_msg);
int  TSMA_get_reply_size( TSXI_FUNC_enum    fc,
                          int               *reply_par_size );
                                
int TSMA_init_thread(void);
int TSMA_terminate_thread(void);
int  TSMA_dispatch_t
                                ( 
                                IN TSXI_FUNC_enum fc,
                                IN TSXI_REQ_MSG_struct *req_msg,   
                                IN int req_len,
                                IN DNXA_REPLY_ADDR replyAddr
                                );
void TSMA_thread_t(void *id);
int TSMA_main(void);






int APIENTRY WinMain(HINSTANCE hInstance,
                     HINSTANCE hPrevInstance,
                     LPSTR     lpCmdLine,
                     int       nCmdShow)
{
	// Check Whether there's already process running

	HANDLE hMutex = OpenMutex(MUTEX_ALL_ACCESS, FALSE, ("TSMA"));
	if (hMutex == NULL)
	{
		hMutex = CreateMutex(NULL, FALSE, ("TSMA"));
	}
	else
	{
		//MessageBox(NULL, ("TSMA had already run."), ("Information"),MB_OK);
		
		return FALSE;
	}

	TSMA_main();

	return 0;

}





// main task
int TSMA_main(void)
{
    int rtn = OK;
    int recvLen = 0;
    TSXI_FUNC_enum func_code;
    char *func = "TSMA_main";
    int reply_par_size = 8;

    DNXA_SERV_ADDR srvaddr[3] = {TSXA_MA_ADDR, TSXA_MA_ADDR_2, DNXA_SERVER_END };

    if( rtn == OK)
    {
        rtn = DNXA_task_init((DNXA_SERV_ADDR *)srvaddr);
        if(rtn != OK)
        {
            TS_LOG(func, "TSMA: DNXA_task_init() error.\n");
            rtn = ERROR;
        }
    }

    DNXA_task_init_t(NULL);    

    if( OK == rtn )
    {
        rtn = TSMA_init_thread();
    }

    Sleep(100);


    // 初始化网络
    MIO_initialize_network();

    Sleep(1000);

    // 启动刷新mio的工位状态寄存器的线程
    tsap_start_read_mio_reg_thread();
        

    if( rtn == OK )
    {
        for(;;)
        {
            memset((void *)&TSMA_req_msg, 0, sizeof(TSXI_REQ_MSG_struct));
            memset((void *)&TSMA_rpl_msg, 0, sizeof(TSXI_RPL_MSG_struct));

			recvLen = 0;

            // 接收请求命令 (应进行接收错误检测)
            rtn = DNXA_receive_request(srvaddr[0], (void *)&TSMA_req_msg,
                    sizeof(TSXI_REQ_MSG_struct), &recvLen, &TSMA_replyAddr, -1);
            if( rtn == OK )
            {
                // 检验收到的数据包是否是TSXA_xxx()或TSXT_xxx()函数发过来的
                if(TSMA_req_msg.nc != TSXI_NUM_CODE)
                {
                    TS_LOG(func, "TSMA_main: illegal request .\n");
                    continue;
                }


                func_code = TSMA_req_msg.func_code;
                // 分发请求
                if( ( func_code >= -1 ) && ( func_code < TSXA_MAX_FUNC_NUM_func_code ) )
                {
                    // 分发请求消息
                    //TSMA_rpl_msg.error_code = TSMA_dispatch(func_code, &TSMA_req_msg, &TSMA_rpl_msg );
                    //TSMA_rpl_msg.func_code = func_code;

                    rtn = TSMA_dispatch_t(func_code, &TSMA_req_msg, recvLen, TSMA_replyAddr);

                }
                else
                {
                    TS_LOG(func, "TSMA_main: recv error func_code %d \n", func_code);
                }

//                if( func_code == TSMA_EXIT_func_code )
//                {
//                    break;              // 退出任务
//                }
            }
            else
            {
                TS_LOG(func, "TSMA_main: DNXA_receive_request error. 0x%x \n", rtn);
            }
        }

        DNXA_task_exit();
    }

    TSMA_terminate_thread();
    
    DNXA_task_exit_t();

    return rtn;
}


// dispatch to call TSAP_xxx
int  TSMA_dispatch( TSXI_FUNC_enum          fc,
                    TSXI_REQ_MSG_struct     *rq_msg,
                    TSXI_RPL_MSG_struct     *rp_msg)
{
    int rtn = 0;

    switch(fc)
    {
        case    TSMA_EXIT_func_code:
            TSAP_MA_task_exit();
            break;

        case    MIO_read_reg_func_code:
            rtn = MIO_read_reg(
                rq_msg->req_par.MIO_read_reg_in_arg.addr,
                &(rp_msg->rpl_par.MIO_read_reg_out_arg.value));
            break;
        case    MIO_write_reg_func_code:
            rtn = MIO_write_reg(
                rq_msg->req_par.MIO_write_reg_in_arg.addr,
                rq_msg->req_par.MIO_write_reg_in_arg.value);
            break;
        case    MIO_read_reg_longs_func_code:
            rtn = MIO_read_reg_longs(
                rq_msg->req_par.MIO_read_reg_longs_in_arg.addr,
                (rp_msg->rpl_par.MIO_read_reg_longs_out_arg.value),
                rq_msg->req_par.MIO_read_reg_longs_in_arg.int32_size);
            break;
        case    MIO_write_reg_longs_func_code:
            rtn = MIO_write_reg_longs(
                rq_msg->req_par.MIO_write_reg_longs_in_arg.addr,
                rq_msg->req_par.MIO_write_reg_longs_in_arg.value,
                rq_msg->req_par.MIO_write_reg_longs_in_arg.int32_size);
            break;
        case    TSXA_sys_control_set_bit_func_code:
            rtn = TSAP_sys_control_set_bit(
                rq_msg->req_par.TSXA_sys_control_set_bit_in_arg.bit_index);
            break;
        case    TSXA_sys_control_clr_func_code:
            rtn = TSAP_sys_control_clr();
            break;
        case    TSXA_mover_control_set_bit_func_code:
            rtn = TSAP_mover_control_set_bit(
                rq_msg->req_par.TSXA_mover_control_set_bit_in_arg.id,
                rq_msg->req_par.TSXA_mover_control_set_bit_in_arg.bit_index);
            break;
        case    TSXA_mover_control_clr_func_code:
            rtn = TSAP_mover_control_clr(
                rq_msg->req_par.TSXA_mover_control_clr_in_arg.id);
            break;
        case    TSXA_sys_initialize_func_code:
            rtn = TSAP_sys_initialize();
            break;
        case    TSXA_sys_terminate_func_code:
            rtn = TSAP_sys_terminate();
            break;
        case    TSXA_sys_start_work_func_code:
            rtn = TSAP_sys_start_work();
            break;
        case    TSXA_sys_stop_work_func_code:
            rtn = TSAP_sys_stop_work();
            break;
        case    TSXA_sys_pause_work_func_code:
            rtn = TSAP_sys_pause_work();
            break;
        case    TSXA_sys_resume_work_func_code:
            rtn = TSAP_sys_resume_work();
            break;
        case    TSXA_sys_stop_func_code:
            rtn = TSAP_sys_stop();
            break;
        case    TSXA_sys_quick_stop_func_code:
            rtn = TSAP_sys_quick_stop();
            break;
        case    TSXA_sys_reset_err_func_code:
            rtn = TSAP_sys_reset_err();
            break;
        case    TSXA_sys_auto_pos_err_reset_on_func_code:
            rtn = TSAP_sys_auto_pos_err_reset_on();
            break;
        case    TSXA_sys_auto_pos_err_reset_off_func_code:
            rtn = TSAP_sys_auto_pos_err_reset_off();
            break;
        case    TSXA_sys_move_to_next_station_all_func_code:
            rtn = TSAP_sys_move_to_next_station_all();
            break;
        case    TSXA_sys_enable_axis_all_func_code:
            rtn = TSAP_sys_enable_axis_all();
            break;
        case    TSXA_sys_disable_axis_all_func_code:
            rtn = TSAP_sys_disable_axis_all();
            break;
        case    TSXA_sys_load_default_mc_func_code:
            rtn = TSAP_sys_load_default_mc();
            break;
        case    TSXA_sys_save_mc_to_flash_func_code:
            rtn = TSAP_sys_save_mc_to_flash();
            break;
        case    TSXA_sys_set_mover_offset_func_code:
            rtn = TSAP_sys_set_mover_offset(
                rq_msg->req_par.TSXA_sys_set_mover_offset_in_arg.axis,
                rq_msg->req_par.TSXA_sys_set_mover_offset_in_arg.offset);
            break;
        case    TSXA_sys_get_mover_offset_func_code:
            rtn = TSAP_sys_get_mover_offset(
                rq_msg->req_par.TSXA_sys_get_mover_offset_in_arg.axis,
                &(rp_msg->rpl_par.TSXA_sys_get_mover_offset_out_arg.offset));
            break;
        case    TSXA_sys_get_status_func_code:
            rtn = TSAP_sys_get_status(
                &(rp_msg->rpl_par.TSXA_sys_get_status_out_arg.sys_status),
                &(rp_msg->rpl_par.TSXA_sys_get_status_out_arg.sys_errno),
                &(rp_msg->rpl_par.TSXA_sys_get_status_out_arg.sys_errinfo)
                );
            break;
        case    TSXA_sys_get_mover_num_func_code:
            rtn = TSAP_sys_get_mover_num(
                &(rp_msg->rpl_par.TSXA_sys_get_mover_num_out_arg.mover_num),
                &(rp_msg->rpl_par.TSXA_sys_get_mover_num_out_arg.station_num));
            break;
        case    TSXA_st_set_station_para_func_code:
            rtn = TSAP_st_set_station_para(
                rq_msg->req_par.TSXA_st_set_station_para_in_arg.id,
                rq_msg->req_par.TSXA_st_set_station_para_in_arg.para);
            break;
        case    TSXA_st_move_next_station_func_code:
            rtn = TSAP_st_move_next_station(
                rq_msg->req_par.TSXA_st_move_next_station_in_arg.st_id);
            break;
        case    TSXA_st_move_next_station_multi_func_code:
            rtn = TSAP_st_move_next_station_multi(
                rq_msg->req_par.TSXA_st_move_next_station_multi_in_arg.station_list,
                rq_msg->req_par.TSXA_st_move_next_station_multi_in_arg.station_list_32_63);
            break;
        case    TSXA_st_qstop_func_code:
            rtn = TSAP_st_qstop(
                rq_msg->req_par.TSXA_st_qstop_in_arg.station_id);
            break;
        case    TSXA_st_qstop_resume_func_code:
            rtn = TSAP_st_qstop_resume(
                rq_msg->req_par.TSXA_st_qstop_resume_in_arg.station_id);
            break;
        case    TSXA_st_enable_func_code:
            rtn = TSAP_st_enable(
                rq_msg->req_par.TSXA_st_enable_in_arg.station_id);
            break;
        case    TSXA_st_disable_func_code:
            rtn = TSAP_st_disable(
                rq_msg->req_par.TSXA_st_disable_in_arg.station_id);
            break;
        case    TSXA_st_get_mover_id_func_code:
            rtn = TSAP_st_get_mover_id(
                rq_msg->req_par.TSXA_st_get_mover_id_in_arg.st_id,
                &(rp_msg->rpl_par.TSXA_st_get_mover_id_out_arg.reached),
                &(rp_msg->rpl_par.TSXA_st_get_mover_id_out_arg.mover_id));
            break;
        case    TSXA_axis_enable_func_code:
            rtn = TSAP_axis_enable(
                rq_msg->req_par.TSXA_axis_enable_in_arg.axis);
            break;
        case    TSXA_axis_disable_func_code:
            rtn = TSAP_axis_disable(
                rq_msg->req_par.TSXA_axis_disable_in_arg.axis);
            break;
        case    TSXA_axis_move_abs_func_code:
            rtn = TSAP_axis_move_abs(
                rq_msg->req_par.TSXA_axis_move_abs_in_arg.axis,
                rq_msg->req_par.TSXA_axis_move_abs_in_arg.pos,
                rq_msg->req_par.TSXA_axis_move_abs_in_arg.vel,
                rq_msg->req_par.TSXA_axis_move_abs_in_arg.acc,
                rq_msg->req_par.TSXA_axis_move_abs_in_arg.dec);
            break;
        case    TSXA_axis_limit_move_abs_func_code:
            rtn = TSAP_axis_limit_move_abs(
                rq_msg->req_par.TSXA_axis_limit_move_abs_in_arg.axis,
                rq_msg->req_par.TSXA_axis_limit_move_abs_in_arg.pos,
                rq_msg->req_par.TSXA_axis_limit_move_abs_in_arg.max_offset,
                rq_msg->req_par.TSXA_axis_limit_move_abs_in_arg.vel);
            break;
        case    TSXA_axis_move_rel_func_code:
            rtn = TSAP_axis_move_rel(
                rq_msg->req_par.TSXA_axis_move_rel_in_arg.axis,
                rq_msg->req_par.TSXA_axis_move_rel_in_arg.pos,
                rq_msg->req_par.TSXA_axis_move_rel_in_arg.vel,
                rq_msg->req_par.TSXA_axis_move_rel_in_arg.acc,
                rq_msg->req_par.TSXA_axis_move_rel_in_arg.dec);
            break;
        case    TSXA_axis_quick_stop_func_code:
            rtn = TSAP_axis_quick_stop(
                rq_msg->req_par.TSXA_axis_quick_stop_in_arg.axis);
            break;
        case    TSXA_axis_stop_func_code:
            rtn = TSAP_axis_stop(
                rq_msg->req_par.TSXA_axis_stop_in_arg.axis);
            break;
        case    TSXA_axis_reset_func_code:
            rtn = TSAP_axis_reset(
                rq_msg->req_par.TSXA_axis_reset_in_arg.axis);
            break;
        case    TSXA_axis_move_vel_func_code:
            rtn = TSAP_axis_move_vel(
                rq_msg->req_par.TSXA_axis_move_vel_in_arg.axis,
                rq_msg->req_par.TSXA_axis_move_vel_in_arg.forward,
                rq_msg->req_par.TSXA_axis_move_vel_in_arg.vel,
                rq_msg->req_par.TSXA_axis_move_vel_in_arg.acc);
            break;
        case    TSXA_axis_change_vel_func_code:
            rtn = TSAP_axis_change_vel(
                rq_msg->req_par.TSXA_axis_change_vel_in_arg.axis,
                rq_msg->req_par.TSXA_axis_change_vel_in_arg.vel);
            break;
        case    TSXA_axis_move_abs_g_func_code:
            rtn = TSAP_axis_move_abs_g(
                rq_msg->req_par.TSXA_axis_move_abs_g_in_arg.num,
                rq_msg->req_par.TSXA_axis_move_abs_g_in_arg.axis_list,
                rq_msg->req_par.TSXA_axis_move_abs_g_in_arg.pos_list,
                rq_msg->req_par.TSXA_axis_move_abs_g_in_arg.vel_list,
                rq_msg->req_par.TSXA_axis_move_abs_g_in_arg.acc_list,
                rq_msg->req_par.TSXA_axis_move_abs_g_in_arg.dec_list);
            break;
        case    TSXA_axis_move_rel_g_func_code:
            rtn = TSAP_axis_move_rel_g(
                rq_msg->req_par.TSXA_axis_move_rel_g_in_arg.num,
                rq_msg->req_par.TSXA_axis_move_rel_g_in_arg.axis_list,
                rq_msg->req_par.TSXA_axis_move_rel_g_in_arg.pos_list,
                rq_msg->req_par.TSXA_axis_move_rel_g_in_arg.vel_list,
                rq_msg->req_par.TSXA_axis_move_rel_g_in_arg.acc_list,
                rq_msg->req_par.TSXA_axis_move_rel_g_in_arg.dec_list);
            break;
        case    TSXA_axis_move_rel_all_func_code:
            rtn = TSAP_axis_move_rel_all(
                rq_msg->req_par.TSXA_axis_move_rel_all_in_arg.num,
                rq_msg->req_par.TSXA_axis_move_rel_all_in_arg.pos_rel,
                rq_msg->req_par.TSXA_axis_move_rel_all_in_arg.vel,
                rq_msg->req_par.TSXA_axis_move_rel_all_in_arg.acc,
                rq_msg->req_par.TSXA_axis_move_rel_all_in_arg.dec);
            break;
        case    TSXA_axis_get_status_func_code:
            rtn = TSAP_axis_get_status(
                rq_msg->req_par.TSXA_axis_get_status_in_arg.axis,
                &(rp_msg->rpl_par.TSXA_axis_get_status_out_arg.mover_status),
                &(rp_msg->rpl_par.TSXA_axis_get_status_out_arg.act_pos),
                &(rp_msg->rpl_par.TSXA_axis_get_status_out_arg.act_vel));
            break;
        case    TSXA_axis_get_status_g_func_code:
            rtn = TSAP_axis_get_status_g(
                rq_msg->req_par.TSXA_axis_get_status_g_in_arg.mover_num,
                rq_msg->req_par.TSXA_axis_get_status_g_in_arg.axis_list,
                (rp_msg->rpl_par.TSXA_axis_get_status_g_out_arg.mover_status_list),
                (rp_msg->rpl_par.TSXA_axis_get_status_g_out_arg.act_vel_list),
                (rp_msg->rpl_par.TSXA_axis_get_status_g_out_arg.act_pos_list));
            break;
        case    TSXA_axis_wait_move_end_func_code:
            rtn = TSAP_axis_wait_move_end(
                rq_msg->req_par.TSXA_axis_wait_move_end_in_arg.axis,
                rq_msg->req_par.TSXA_axis_wait_move_end_in_arg.timeout);
            break;
        case    TSXA_axis_wait_move_end_g_func_code:
            rtn = TSAP_axis_wait_move_end_g(
                rq_msg->req_par.TSXA_axis_wait_move_end_g_in_arg.num,
                rq_msg->req_par.TSXA_axis_wait_move_end_g_in_arg.axis_list,
                rq_msg->req_par.TSXA_axis_wait_move_end_g_in_arg.timeout);
            break;
        case    TSXA_get_mover_pos_func_code:
            rtn = TSAP_get_mover_pos(
                rq_msg->req_par.TSXA_get_mover_pos_in_arg.axis,
                &(rp_msg->rpl_par.TSXA_get_mover_pos_out_arg.pos),
                &(rp_msg->rpl_par.TSXA_get_mover_pos_out_arg.vel));
            break;
        case    TSXA_get_mover_pos_group_func_code:
            rtn = TSAP_get_mover_pos_group(
                rq_msg->req_par.TSXA_get_mover_pos_group_in_arg.num,
                rq_msg->req_par.TSXA_get_mover_pos_group_in_arg.axis_list,
                (rp_msg->rpl_par.TSXA_get_mover_pos_group_out_arg.pos_list));
            break;
        case    TSXA_set_motion_parameter_func_code:
            rtn = TSAP_set_motion_parameter(
                rq_msg->req_par.TSXA_set_motion_parameter_in_arg.axis,
                rq_msg->req_par.TSXA_set_motion_parameter_in_arg.vel,
                rq_msg->req_par.TSXA_set_motion_parameter_in_arg.acc,
                rq_msg->req_par.TSXA_set_motion_parameter_in_arg.dec);
            break;
        case    TSXA_get_motion_parameter_func_code:
            rtn = TSAP_get_motion_parameter(
                rq_msg->req_par.TSXA_get_motion_parameter_in_arg.axis,
                &(rp_msg->rpl_par.TSXA_get_motion_parameter_out_arg.vel),
                &(rp_msg->rpl_par.TSXA_get_motion_parameter_out_arg.acc),
                &(rp_msg->rpl_par.TSXA_get_motion_parameter_out_arg.dec));
            break;
        case    TSXA_set_global_motion_parameter_func_code:
            rtn = TSAP_set_global_motion_parameter(
                rq_msg->req_par.TSXA_set_global_motion_parameter_in_arg.vel,
                rq_msg->req_par.TSXA_set_global_motion_parameter_in_arg.acc,
                rq_msg->req_par.TSXA_set_global_motion_parameter_in_arg.dec);
            break;
        case    TSXA_get_global_motion_parameter_func_code:
            rtn = TSAP_get_global_motion_parameter(
                &(rp_msg->rpl_par.TSXA_get_global_motion_parameter_out_arg.vel),
                &(rp_msg->rpl_par.TSXA_get_global_motion_parameter_out_arg.acc),
                &(rp_msg->rpl_par.TSXA_get_global_motion_parameter_out_arg.dec),
                &(rp_msg->rpl_par.TSXA_get_global_motion_parameter_out_arg.quick_stop_acc),
                &(rp_msg->rpl_par.TSXA_get_global_motion_parameter_out_arg.jerk) );
            break;
        case    TSXA_axis_disable_all_func_code:
            rtn = TSAP_axis_disable_all(
                rq_msg->req_par.TSXA_axis_disable_all_in_arg.num);
            break;
        case    TSXA_axis_enable_all_func_code:
            rtn = TSAP_axis_enable_all(
                rq_msg->req_par.TSXA_axis_enable_all_in_arg.num);
            break;
        case    TSXA_st_get_all_mover_id_func_code:
            rtn = TSAP_st_get_all_mover_id(
                &(rp_msg->rpl_par.TSXA_st_get_all_mover_id_out_arg.st_reached_num),
                (int *)&(rp_msg->rpl_par.TSXA_st_get_all_mover_id_out_arg.st_reached_id_list),
                (int *)&(rp_msg->rpl_par.TSXA_st_get_all_mover_id_out_arg.reaced_mover_id_list));
            break;
        case    TSXA_st_get_all_mover_id_32_func_code:
            rtn = TSAP_st_get_all_mover_id_32(
                &(rp_msg->rpl_par.TSXA_st_get_all_mover_id_32_out_arg.st_reached_num),
                (int *)&(rp_msg->rpl_par.TSXA_st_get_all_mover_id_32_out_arg.st_reached_id_list),
                (int *)&(rp_msg->rpl_par.TSXA_st_get_all_mover_id_32_out_arg.reaced_mover_id_list));
            break;
        case    TSXA_st_get_occupy_func_code:
            rtn = TSAP_st_get_occupy(
                rq_msg->req_par.TSXA_st_get_occupy_in_arg.st_id,
                &(rp_msg->rpl_par.TSXA_st_get_occupy_out_arg.has));
            break;
        case    TSXA_st_set_allow_entering_func_code:
            rtn = TSAP_st_set_allow_entering(
                rq_msg->req_par.TSXA_st_set_allow_entering_in_arg.st_id,
                rq_msg->req_par.TSXA_st_set_allow_entering_in_arg.allow);
            break;
        case    TSXA_get_sys_state_func_code:
            rtn = TSAP_get_sys_state(
                &(rp_msg->rpl_par.TSXA_get_sys_state_out_arg.inited),
                &(rp_msg->rpl_par.TSXA_get_sys_state_out_arg.autoworked));
            break;
        case    TSXA_st_get_pos_func_code:
            rtn = TSAP_st_get_pos(
                rq_msg->req_par.TSXA_st_get_pos_in_arg.st_id,
                &(rp_msg->rpl_par.TSXA_st_get_pos_out_arg.pos));
            break;
        case    TSXA_st_limit_func_code:
            rtn = TSAP_st_limit(
                rq_msg->req_par.TSXA_st_limit_in_arg.station_id,
				rq_msg->req_par.TSXA_st_limit_in_arg.station_op );
            break;
        case    TSXA_mv_ison_func_code:
            rtn = TSAP_mv_ison(
                rq_msg->req_par.TSXA_mv_ison_in_arg.mover_id,
                &(rp_msg->rpl_par.TSXA_mv_ison_out_arg.yes));
            break;
        case    TSXA_st_set_station_pv_func_code:
            rtn = TSAP_st_set_station_pv(
                rq_msg->req_par.TSXA_st_set_station_pv_in_arg.id,
				rq_msg->req_par.TSXA_st_set_station_pv_in_arg.pos,
				rq_msg->req_par.TSXA_st_set_station_pv_in_arg.vel,
				rq_msg->req_par.TSXA_st_set_station_pv_in_arg.save_to_flash
				);
            break;
        case    TSXA_st_act_limit_func_code:
            rtn = TSAP_st_act_limit(
                rq_msg->req_par.TSXA_st_act_limit_in_arg.station_id,
                rq_msg->req_par.TSXA_st_act_limit_in_arg.limit_en
                );
            break;

        case    TSXA_st_dianjiao_set_func_code:
            rtn = TSAP_st_dianjiao_set(
                rq_msg->req_par.TSXA_st_dianjiao_set_in_arg.st_num,
                rq_msg->req_par.TSXA_st_dianjiao_set_in_arg.st_list
                );
            break;
        case    TSXA_st_zhuzhuang_set_func_code:
            rtn = TSAP_st_zhuzhuang_set(
                rq_msg->req_par.TSXA_st_zhuzhuang_set_in_arg.st_num,
                rq_msg->req_par.TSXA_st_zhuzhuang_set_in_arg.st_list
                );
            break;
            


        default:
            break;
    }

    return rtn;
}


// 获取回应数据的数据结构内容大小
int  TSMA_get_reply_size( TSXI_FUNC_enum         fc,
                          int                    *reply_par_size )
{
    int rtn = 0;
    int size = 8;

    switch(fc)
    {
        case    TSMA_EXIT_func_code:
            size = 8;
            break;
        case    MIO_read_reg_func_code:
                size = sizeof(TSXI_MIO_read_reg_rpl_struct);
                break;
        case    MIO_write_reg_func_code:
                size = sizeof(TSXI_MIO_write_reg_rpl_struct);
                break;
        case    MIO_read_reg_longs_func_code:
                size = sizeof(TSXI_MIO_read_reg_longs_rpl_struct);
                break;
        case    MIO_write_reg_longs_func_code:
                size = sizeof(TSXI_MIO_write_reg_longs_rpl_struct);
                break;
        
        case TSXA_sys_control_set_bit_func_code:
                size = sizeof(TSXI_TSXA_sys_control_set_bit_rpl_struct);
                break;
                 
        case TSXA_sys_control_clr_func_code:     
            size = sizeof(TSXI_TSXA_sys_control_clr_rpl_struct);
            break;
                     
        case TSXA_mover_control_set_bit_func_code:                  
            size =  sizeof(TSXI_TSXA_mover_control_set_bit_rpl_struct);
            break;
               
        case TSXA_mover_control_clr_func_code:   
            size = sizeof(TSXI_TSXA_mover_control_clr_rpl_struct);
            break;
                   
        case TSXA_sys_initialize_func_code:      
            size = sizeof(TSXI_TSXA_sys_initialize_rpl_struct);
            break;
                      
        case TSXA_sys_terminate_func_code:       
            size = sizeof(TSXI_TSXA_sys_terminate_rpl_struct);
            break;
                       
        case TSXA_sys_start_work_func_code:      
            size = sizeof(TSXI_TSXA_sys_start_work_rpl_struct);
            break;
                      
        case TSXA_sys_stop_work_func_code:       
            size = sizeof(TSXI_TSXA_sys_stop_work_rpl_struct);
            break;
                       
        case TSXA_sys_pause_work_func_code:      
            size = sizeof(TSXI_TSXA_sys_pause_work_rpl_struct);
            break;
                      
        case TSXA_sys_resume_work_func_code:     
            size = sizeof(TSXI_TSXA_sys_resume_work_rpl_struct);
            break;
                     
        case TSXA_sys_stop_func_code:            
            size = sizeof(TSXI_TSXA_sys_stop_rpl_struct);
            break;
                            
        case TSXA_sys_quick_stop_func_code:      
            size = sizeof(TSXI_TSXA_sys_quick_stop_rpl_struct);
            break;
                      
        case TSXA_sys_reset_err_func_code:       
            size = sizeof(TSXI_TSXA_sys_reset_err_rpl_struct);
            break;
                       
        case TSXA_sys_auto_pos_err_reset_on_func_code:              
            size =  sizeof(TSXI_TSXA_sys_auto_pos_err_reset_on_rpl_struct);
            break;
           
        case TSXA_sys_auto_pos_err_reset_off_func_code:             
            size =  sizeof(TSXI_TSXA_sys_auto_pos_err_reset_off_rpl_struct);
            break;
          
        case TSXA_sys_move_to_next_station_all_func_code:           
            size =  sizeof(TSXI_TSXA_sys_move_to_next_station_all_rpl_struct);
            break;

        case TSXA_sys_enable_axis_all_func_code: 
            size = sizeof(TSXI_TSXA_sys_enable_axis_all_rpl_struct);
            break;
                 
        case TSXA_sys_disable_axis_all_func_code:
            size = sizeof(TSXI_TSXA_sys_disable_axis_all_rpl_struct);
            break;
                
        case TSXA_sys_load_default_mc_func_code: 
            size = sizeof(TSXI_TSXA_sys_load_default_mc_rpl_struct);
            break;
                 
        case TSXA_sys_save_mc_to_flash_func_code:
            size = sizeof(TSXI_TSXA_sys_save_mc_to_flash_rpl_struct);
            break;
                
        case TSXA_sys_set_mover_offset_func_code:
            size = sizeof(TSXI_TSXA_sys_set_mover_offset_rpl_struct);
            break;
                
        case TSXA_sys_get_mover_offset_func_code:
            size = sizeof(TSXI_TSXA_sys_get_mover_offset_rpl_struct);
            break;
                
        case TSXA_sys_get_status_func_code:      
            size = sizeof(TSXI_TSXA_sys_get_status_rpl_struct);
            break;
                      
        case TSXA_sys_get_mover_num_func_code:   
            size = sizeof(TSXI_TSXA_sys_get_mover_num_rpl_struct);
            break;
                   
        case TSXA_st_set_station_para_func_code: 
            size = sizeof(TSXI_TSXA_st_set_station_para_rpl_struct);
            break;
                 
        case TSXA_st_move_next_station_func_code:
            size = sizeof(TSXI_TSXA_st_move_next_station_rpl_struct);
            break;
                
        case TSXA_st_move_next_station_multi_func_code:             
            size =  sizeof(TSXI_TSXA_st_move_next_station_multi_rpl_struct);
            break;
          
        case TSXA_st_qstop_func_code:            
            size = sizeof(TSXI_TSXA_st_qstop_rpl_struct);
            break;
                            
        case TSXA_st_qstop_resume_func_code:     
            size = sizeof(TSXI_TSXA_st_qstop_resume_rpl_struct);
            break;
                     
        case TSXA_st_enable_func_code:           
            size = sizeof(TSXI_TSXA_st_enable_rpl_struct);
            break;
                           
        case TSXA_st_disable_func_code:          
            size = sizeof(TSXI_TSXA_st_disable_rpl_struct);
            break;
                          
        case TSXA_st_get_mover_id_func_code:     
            size = sizeof(TSXI_TSXA_st_get_mover_id_rpl_struct);
            break;
                     
        case TSXA_axis_enable_func_code:         
        size = sizeof(TSXI_TSXA_axis_enable_rpl_struct);
        break;
                         
        case TSXA_axis_disable_func_code:        
        size = sizeof(TSXI_TSXA_axis_disable_rpl_struct);
        break;
                        
        case TSXA_axis_move_abs_func_code:       
        size = sizeof(TSXI_TSXA_axis_move_abs_rpl_struct);
        break;
                       
        case TSXA_axis_limit_move_abs_func_code: 
        size = sizeof(TSXI_TSXA_axis_limit_move_abs_rpl_struct);
        break;
                 
        case TSXA_axis_move_rel_func_code:       
        size = sizeof(TSXI_TSXA_axis_move_rel_rpl_struct);
        break;
                       
        case TSXA_axis_quick_stop_func_code:     
        size = sizeof(TSXI_TSXA_axis_quick_stop_rpl_struct);
        break;
                     
        case TSXA_axis_stop_func_code:           
        size = sizeof(TSXI_TSXA_axis_stop_rpl_struct);
        break;
                           
        case TSXA_axis_reset_func_code:          
        size = sizeof(TSXI_TSXA_axis_reset_rpl_struct);
        break;
                          
        case TSXA_axis_move_vel_func_code:       
        size = sizeof(TSXI_TSXA_axis_move_vel_rpl_struct);
        break;
                       
        case TSXA_axis_change_vel_func_code:     
        size = sizeof(TSXI_TSXA_axis_change_vel_rpl_struct);
        break;
                     
        case TSXA_axis_move_abs_g_func_code:     
        size = sizeof(TSXI_TSXA_axis_move_abs_g_rpl_struct);
        break;
                     
        case TSXA_axis_move_rel_g_func_code:     
        size = sizeof(TSXI_TSXA_axis_move_rel_g_rpl_struct);
        break;
                     
        case TSXA_axis_move_rel_all_func_code:   
        size = sizeof(TSXI_TSXA_axis_move_rel_all_rpl_struct);
        break;
                   
        case TSXA_axis_get_status_func_code:     
        size = sizeof(TSXI_TSXA_axis_get_status_rpl_struct);
        break;
                     
        case TSXA_axis_get_status_g_func_code:   
        size = sizeof(TSXI_TSXA_axis_get_status_g_rpl_struct);
        break;
                   
        case TSXA_axis_wait_move_end_func_code:  
        size = sizeof(TSXI_TSXA_axis_wait_move_end_rpl_struct);
        break;
                  
        case TSXA_axis_wait_move_end_g_func_code:
        size = sizeof(TSXI_TSXA_axis_wait_move_end_g_rpl_struct);
        break;
                
        case TSXA_get_mover_pos_func_code:       
        size = sizeof(TSXI_TSXA_get_mover_pos_rpl_struct);
        break;
                       
        case TSXA_get_mover_pos_group_func_code: 
        size = sizeof(TSXI_TSXA_get_mover_pos_group_rpl_struct);
        break;
                 
        case TSXA_set_motion_parameter_func_code:
        size = sizeof(TSXI_TSXA_set_motion_parameter_rpl_struct);
        break;
                
        case TSXA_get_motion_parameter_func_code:
        size = sizeof(TSXI_TSXA_get_motion_parameter_rpl_struct);
        break;
                
        case TSXA_set_global_motion_parameter_func_code:            
        size =  sizeof(TSXI_TSXA_set_global_motion_parameter_rpl_struct);
        break;
         
        case TSXA_get_global_motion_parameter_func_code:            
        size =  sizeof(TSXI_TSXA_get_global_motion_parameter_rpl_struct);
        break;
         
        case TSXA_axis_disable_all_func_code:    
        size = sizeof(TSXI_TSXA_axis_disable_all_rpl_struct);
        break;
                    
        case TSXA_axis_enable_all_func_code:     
        size = sizeof(TSXI_TSXA_axis_enable_all_rpl_struct);
        break;
                     
        case TSXA_st_get_all_mover_id_func_code: 
        size = sizeof(TSXI_TSXA_st_get_all_mover_id_rpl_struct);
        break;
                 
        case TSXA_st_get_all_mover_id_32_func_code:                 
        size =  sizeof(TSXI_TSXA_st_get_all_mover_id_32_rpl_struct);
        break;
              
        case TSXA_st_get_occupy_func_code:       
        size = sizeof(TSXI_TSXA_st_get_occupy_rpl_struct);
        break;
                       
        case TSXA_st_set_allow_entering_func_code:                  
        size =  sizeof(TSXI_TSXA_st_set_allow_entering_rpl_struct);
        break;
               
        case TSXA_get_sys_state_func_code:       
        size = sizeof(TSXI_TSXA_get_sys_state_rpl_struct);
        break;
                       
        case TSXA_st_get_pos_func_code:          
        size = sizeof(TSXI_TSXA_st_get_pos_rpl_struct);
        break;
                          
        case TSXA_st_limit_func_code:            
        size = sizeof(TSXI_TSXA_st_limit_rpl_struct);
        break;
                            
        case TSXA_mv_ison_func_code:             
        size = sizeof(TSXI_TSXA_mv_ison_rpl_struct);
        break;
                             
        case TSXA_st_set_station_pv_func_code:   
        size = sizeof(TSXI_TSXA_st_set_station_pv_rpl_struct);
        break;
                   
        case TSXA_st_act_limit_func_code:        
        size = sizeof(TSXI_TSXA_st_act_limit_rpl_struct);
        break;
            
        case TSXA_st_dianjiao_set_func_code:        
        size = sizeof(TSXI_TSXA_st_dianjiao_set_rpl_struct);
        break;
        case TSXA_st_zhuzhuang_set_func_code:        
        size = sizeof(TSXI_TSXA_st_zhuzhuang_set_rpl_struct);
        break;

        default:
            size = 8;
            break;
    }

    if( reply_par_size != NULL )
    {
       *reply_par_size = size + 8;			// TSXI_RPL_MSG_struct结构体大小比单个函数的回应消息还要加8字节
    }
    
    return rtn;
}



int TSMA_init_thread(void)
{
    int rtn = OK;
    int i = 0;
    char pipe_name[32] = { 0 };

    g_TSMA_thread_stop = FALSE;
    
    // 建立多个thread
    for( i = 0; i < TSMA_MAX_THREAD_NUM; i++ )
    {
	    _beginthread(TSMA_thread_t, 16*1024*1024, (void *)&i);
        Sleep(50);
    }

    Sleep(100);
    
    // client与各个pipe建立连接
    for( i = 0; i < TSMA_MAX_THREAD_NUM; i++ )
    {
        memset((void *)pipe_name, 0, sizeof(pipe_name));
        sprintf(pipe_name, "\\\\.\\pipe\\TSMA_pipe_%d", i);
        GFXA_client_wait_pipe_ready(pipe_name, &g_TSMA_pipe_client_fd[i], -1); 
    }

    return rtn;
}


int TSMA_terminate_thread(void)
{
    int rtn = OK;
    
    g_TSMA_thread_stop = TRUE;

    return rtn;
}



// server端多线程分发
int  TSMA_dispatch_t
                                ( 
                                IN TSXI_FUNC_enum fc,
                                IN TSXI_REQ_MSG_struct *req_msg,   
                                IN int req_len,
                                IN DNXA_REPLY_ADDR replyAddr
                                )
{
    int rtn = OK;
    int actLen = 0;
    int pipe_id = 0;
    BOOL multi_thread = FALSE;
    TSXI_RPL_MSG_struct reply;
    int reply_size = 0;


    // 将DN回应地址加入到数据包中
    req_msg->reply_addr = replyAddr;

//DTXA_trace_t("TS", DTXA_TRACE_DEBUG, "TSMA_main", "010");


#if 1

    // 根据fc及axis，分发处理，如果需要多线程并行处理的任务就发给相应不同的pipe
    switch(fc)
    {
        case    TSMA_EXIT_func_code:
            TSAP_MA_task_exit();
            break;

        case     MIO_read_reg_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MIO_READ_WRITE;
            break;
        case     MIO_write_reg_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MIO_READ_WRITE;
            break;
        case     MIO_read_reg_longs_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MIO_READ_WRITE;
            break;
        case     MIO_write_reg_longs_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MIO_READ_WRITE;
            break;
        case     TSXA_sys_control_set_bit_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_control_clr_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_mover_control_set_bit_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_mover_control_clr_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case    TSXA_sys_initialize_func_code:
            rtn = TSAP_sys_initialize();
            break;
        case    TSXA_sys_terminate_func_code:
            rtn = TSAP_sys_terminate();
            break;
        case     TSXA_sys_start_work_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_stop_work_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_pause_work_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_resume_work_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_stop_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
            
        case     TSXA_sys_quick_stop_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
            
        case     TSXA_sys_reset_err_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_auto_pos_err_reset_on_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_auto_pos_err_reset_off_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_move_to_next_station_all_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_enable_axis_all_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_disable_axis_all_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_load_default_mc_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_save_mc_to_flash_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_set_mover_offset_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_get_mover_offset_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_get_status_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_sys_get_mover_num_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
        case     TSXA_st_set_station_para_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;

 /*           
            TSXA_st_move_next_station_func_code,
            TSXA_st_move_next_station_multi_func_code,
            TSXA_st_qstop_func_code,
            TSXA_st_qstop_resume_func_code,
            TSXA_st_enable_func_code,
            TSXA_st_disable_func_code,
            TSXA_st_get_mover_id_func_code,
            TSXA_axis_enable_func_code,
            TSXA_axis_disable_func_code,
            TSXA_axis_move_abs_func_code,
            TSXA_axis_limit_move_abs_func_code,
            TSXA_axis_move_rel_func_code,
            TSXA_axis_quick_stop_func_code,
            TSXA_axis_stop_func_code,
            TSXA_axis_reset_func_code,
            TSXA_axis_move_vel_func_code,
            TSXA_axis_change_vel_func_code,
            TSXA_axis_move_abs_g_func_code,
            TSXA_axis_move_rel_g_func_code,
            TSXA_axis_move_rel_all_func_code,
            TSXA_axis_get_status_func_code,
            TSXA_axis_get_status_g_func_code,
            TSXA_axis_wait_move_end_func_code,
            TSXA_axis_wait_move_end_g_func_code,
            TSXA_get_mover_pos_func_code,
            TSXA_get_mover_pos_group_func_code,
            TSXA_set_motion_parameter_func_code,
            TSXA_get_motion_parameter_func_code,
            TSXA_set_global_motion_parameter_func_code,
            TSXA_get_global_motion_parameter_func_code,
            TSXA_axis_disable_all_func_code,
            TSXA_axis_enable_all_func_code,
            TSXA_st_get_all_mover_id_func_code,
            TSXA_st_get_all_mover_id_32_func_code,
            TSXA_st_get_occupy_func_code,
            TSXA_st_set_allow_entering_func_code,
            TSXA_get_sys_state_func_code,
            TSXA_st_get_pos_func_code,
            TSXA_st_limit_func_code,
            TSXA_mv_ison_func_code,
            TSXA_st_set_station_pv_func_code,
            TSXA_st_act_limit_func_code,
*/
        case     TSXA_st_dianjiao_set_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_DIANJIAO_THREAD;
            break;
        case     TSXA_st_zhuzhuang_set_func_code:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_ZHUZHUANG_THREAD;
            break;

        default:
            multi_thread = TRUE;
            pipe_id = TSMA_PIPE_NUM_MAIN_THREAD;
            break;
    }

    
#endif  // 0


    // 需要多线程处理，发送给相应的pipe处理线程，处理线程里面发送回应消息
    if( multi_thread )
    {
        rtn = GFXA_write_pipe(g_TSMA_pipe_client_fd[pipe_id], (char *)req_msg, req_len, &actLen);
    }
    else
    {       
        // 就在主任务里直接发送回应消息
        reply.error_code = rtn;
        reply.func_code = fc;
        if( req_msg->reply_wanted )
        {
        	reply_size = 8;         // 没有返回参数
            rtn = DNXA_send_reply(replyAddr, (void *)&reply, reply_size);
        }
    }
    
    return rtn;
}





void TSMA_thread_t(void *id)
{
    int rtn = OK;
    HANDLE pipe_fd = NULL;
    int pipe_id = 0;
    int bytes = 0;
    char pipe_name[32] = { 0 };
    char buf[TSMA_MAX_PIPE_DATA_SIZE] = { 0 };
    TSXI_REQ_MSG_struct *request = NULL;
    TSXI_RPL_MSG_struct reply;
    TSXI_FUNC_enum fc;
    int reply_size = 0;
    DNXA_REPLY_ADDR reply_addr = 0;

    DNXA_task_init_t(NULL);             // add by frank 2017.5.27
    
    pipe_id = *(int *)(id);

    {
        sprintf(pipe_name, "\\\\.\\pipe\\TSMA_pipe_%d", pipe_id);

        rtn = GFXA_create_pipe(pipe_name, 65536, TRUE, 1000, &g_TSMA_pipe_server_fd[pipe_id]); 

        // 等待client连接pipe
        rtn = GFXA_server_wait_pipe(g_TSMA_pipe_server_fd[pipe_id]);  
        
        for(;;)
        {
            // 接收数据
            memset((void *)buf, 0, sizeof(buf));
            memset((void *)&reply, 0, sizeof(TSXI_RPL_MSG_struct));
            rtn = GFXA_read_pipe(g_TSMA_pipe_server_fd[pipe_id], buf, TSMA_MAX_PIPE_DATA_SIZE, &bytes);
            if( OK == rtn )
            {
                if(bytes > 0 )
                {
                    request = (TSXI_REQ_MSG_struct *)buf;
                    fc = request->func_code;
                    reply_addr = request->reply_addr;
                    rtn = TSMA_dispatch(fc, request, &reply);

                    // 发送回应消息
                    if( request->reply_wanted )
                    {
                    	TSMA_get_reply_size(fc, &reply_size);
                        reply.func_code = fc;
                        reply.error_code = rtn;
                        rtn = DNXA_send_reply(reply_addr, (void *)&reply, reply_size);
                    }
                }
            }

            if( g_TSMA_thread_stop )
            {
                break;
            }
            
        }

        CloseHandle(g_TSMA_pipe_server_fd[pipe_id]);
        g_TSMA_pipe_server_fd[pipe_id] = NULL;
    }

    DNXA_task_exit_t();

    return;
}


